.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. fokawa_qt test_fokawa_qt
clean: FORCE
	$(MAKE) -C .. fokawa_qt_clean test_fokawa_qt_clean
check: FORCE
	$(MAKE) -C .. test_fokawa_qt_check
fokawa-qt fokawa-qt.exe: FORCE
	 $(MAKE) -C .. fokawa_qt
